### ISSUE TITLE
Why does Scan.parse() output SIM card data & make network requests?

### ISSUE THREAD

**Issue by AndrewCPU** [flutter-package/flutter_scan#32]
Why does Scan.parse() output SIM card data & make network requests?

```
I/ScankitSDK(11991): ScankitSDK Version: SCANPLUS2.1.0.300
E/ActivityThread(11991): Failed to find provider info for com.huawei.hms
W/dynamic-api_DynamicModule(11991): 11991-12040|null|com.huawei.hms.feature.dynamic.DynamicModule|getRemoteVersion|75|Query remote module:huawei_module_scankit exception:com.huawei.hms.feature.dynamic.DynamicModule$a: failed to Query remote version.
I/ScankitSDK(11991): local Version is Higher20100300
I/Creator (11991): newRemoteDecoderDelegate()
E/SecurityResourcesReader(11991): KEY is null return def directly
E/HaLog   (11991): initValue RuntimeException
I/ScankitDecode(11991): static initializer: InitModuleBegin
I/MsModel (11991): load model....detect.ms
I/MsModel (11991): inputStreamandroid.content.res.AssetManager$AssetInputStream@fd4f494
I/MsModel (11991): ms anrchos....anchors.bin
I/MsModel (11991): 2inputStreamandroid.content.res.AssetManager$AssetInputStream@ea96b3d
I/MsModel (11991): load angle model....angle.ms
I/MsModel (11991): 3inputStreamandroid.content.res.AssetManager$AssetInputStream@afd6f32
I/ScankitDecode(11991): static initializer: InitModuleEnd
I/ScankitDecode(11991): scankit mode:FULLSDK1
I/OpencvJNI(11991): start load method
I/MS_PREDICT(11991): |11991|InnerContext[79]|: Hw cap support SIMD Dot Product, hwcap: 0x119fff
I/MS_PREDICT(11991): |11991|InnerContext[79]|: Hw cap support SIMD Dot Product, hwcap: 0x119fff
I/ScankitDecode(11991): ScanCode successful
I/flutter (11991): babbef3e-5ce4-4528-8a1d-50bc47ce5f24
I/NetworkKit_CountryCodeBean(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getVendorCountryCode|39|countryCode by ro.hw.country is: UNKNOWN
I/NetworkKit_CountryCodeBean(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|getSimCountryCode|74|countryCode by SimCountryIso is: us
I/NetworkKit_CountryCodeBean(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean|init|32|get issue_country code from SIM_COUNTRY
I/NetworkKit_Cc(11991): ScanHiAnalytics|CountryCodeBean.java|com.huawei.hms.scankit.p.Cc|a|4|getCountryCode unknown
I/ScanHiAnalytics(11991): getCollectURL:localCountryCode US
I/NetworkKit_c(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.a.c|a|48|app version changed! old version{} and new version{1}
I/NetworkKit_c(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.a.c|a|48|app version changed! old version{} and new version{1}
I/NetworkKit_LocalManagerV2(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.b.d|<init>|32|appConfigName isnull
W/NetworkKit_c(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.d.c|a|70|local config file is not exist.filename is {grs_app_global_route_config.json}
W/NetworkKit_IOUtil(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.common.IoUtils|closeSecure|17|closeable is null
W/NetworkKit_c(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.network.grs.d.c|a|70|local config file is not exist.filename is {grs_sdk_global_route_config.json}
W/NetworkKit_IOUtil(11991): ScanHiAnalytics -->NetworkKit_GRS_GrsClient-Init_0|null|com.huawei.hms.framework.common.IoUtils|closeSecure|17|closeable is null
W/NetworkKit_AbstractLocalManager(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.b.a|a|14|application data is null.
W/NetworkKit_AbstractLocalManager(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.b.a|a|22|addresses not found by routeby in local config{com.huawei.cloud.mlkithianalytics}
I/NetworkKit_j(11991): NetworkKit_GRS_RequestController-Task_2 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.c.j|call|6|Post call execute
I/SecurityComp115301: SecureSSLSocketFactory(11991): createSocket
I/SecurityComp115301: SecureSSLSocketFactory(11991): set default protocols
I/SecurityComp115301: SecureSSLSocketFactory(11991): set default cipher suites
I/SecurityComp115301: SecureX509TrustManager(11991): checkServerTrusted begin ,server ca chain size is : 2
I/SecurityComp115301: SecureX509TrustManager(11991): check server i : 0
I/SecurityComp115301: SecureX509TrustManager(11991): client root ca size is : 1
W/NetworkKit_f(11991): NetworkKit_GRS_RequestController-Task_2 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.c.f|n|155|GrsResponse GrsResponse(String result) JSONException
W/NetworkKit_f(11991): org.json.JSONException: N* *a*u* *o* *e*v*c*s
W/NetworkKit_f(11991): 	at org.json.JSONObject.get(JSONObject.java:403)
W/NetworkKit_f(11991): 	at org.json.JSONObject.getJSONObject(JSONObject.java:623)
W/NetworkKit_f(11991): 	at com.huawei.hms.framework.network.grs.c.f.n(Unknown Source:123)
W/NetworkKit_f(11991): 	at com.huawei.hms.framework.network.grs.c.f.q(Unknown Source:3)
W/NetworkKit_f(11991): 	at com.huawei.hms.framework.network.grs.c.f.<init>(Unknown Source:41)
W/NetworkKit_f(11991): 	at com.huawei.hms.framework.network.grs.c.j.call(Unknown Source:148)
W/NetworkKit_f(11991): 	at com.huawei.hms.framework.network.grs.c.j.call(Unknown Source:0)
W/NetworkKit_f(11991): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/NetworkKit_a(11991): NetworkKit_GRS_RequestController-Task_2 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.a.a|a|11|update cache from server failed
I/NetworkKit_e(11991): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_2|null|com.huawei.hms.framework.network.grs.c.e|a|81|grs request return body is not null and is OK.
W/NetworkKit_HianalyticsHelper(11991): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_2|null|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|<init>|30|maybe you need add Hianalytics sdk
I/NetworkKit_HianalyticsHelper(11991): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_2|null|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|isEnableReportNoSeed|9|Hianalytics sdk need to be initialized
I/NetworkKit_a(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.a|a|77|access local config for return a domain.
W/NetworkKit_AbstractLocalManager(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.b.a|a|14|application data is null.
W/NetworkKit_AbstractLocalManager(11991): ScanHiAnalytics|null|com.huawei.hms.framework.network.grs.b.a|a|22|addresses not found by routeby in local config{com.huawei.cloud.mlkithianalytics}
I/ScanHiAnalytics(11991): grs get url success: null  countryCode = US
I/OpenGLRenderer(11991): Davey! duration=304549ms; Flags=0, FrameTimelineVsyncId=4114979, IntendedVsync=54995046966916, Vsync=54995046966916, InputEventId=0, HandleInputStart=54995047268388, AnimationStart=54995047269405, PerformTraversalsStart=54995047270056, DrawStart=54995047524614, FrameDeadline=54995071900249, FrameInterval=54995047264482, FrameStartTime=8333333, SyncQueued=54995047727128, SyncStart=54995047759843, IssueDrawCommandsStart=54995047788326, SwapBuffers=54995050503495, FrameCompleted=55299596658267, DequeueBufferDuration=1084554, QueueBufferDuration=613688, GpuCompleted=55299596658267, SwapBuffersCompleted=54995051154822, DisplayPresentTime=0, 
```

**Comment by chavesgu** [comment]
I did not use net work,it's may be used by `com.huawei.hms`

**Comment by AndrewCPU** [comment]
Why is the Huawei package required?

**Comment by chavesgu** [comment]
@AndrewCPU    You can check this [agreement](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sdk-data-security-0000001050043971)

**Comment by AndrewCPU** [comment]
> @AndrewCPU    You can check this [agreement](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sdk-data-security-0000001050043971)

Appreciate your response.
