### ISSUE TITLE
App Crash (release mode) After Upgrade to Flutter 2.10.1

### ISSUE THREAD

**Issue by saelco** [flutter-package/flutter_scan#41]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.10.1         |
| Plugin version       |          1.6.0     |
| Android version      |      All version         |
| iOS version          |               |
| Xcode version        |               |

E/AndroidRuntime(28903): Process: myproject.id, PID: 28903
E/AndroidRuntime(28903): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(28903): 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
E/AndroidRuntime(28903): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(28903): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(28903): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(28903): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
E/AndroidRuntime(28903): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(28903): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(28903): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime(28903): Caused by: java.lang.AssertionError: impossible
E/AndroidRuntime(28903): 	at java.lang.Enum$1.create(Enum.java:269)
E/AndroidRuntime(28903): 	at java.lang.Enum$1.create(Enum.java:260)
E/AndroidRuntime(28903): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
E/AndroidRuntime(28903): 	at java.lang.Enum.getSharedConstants(Enum.java:286)
E/AndroidRuntime(28903): 	at java.lang.Class.getEnumConstantsShared(Class.java:2291)
E/AndroidRuntime(28903): 	at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
E/AndroidRuntime(28903): 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:752)
E/AndroidRuntime(28903): 	at java.util.EnumMap.<init>(EnumMap.java:137)
E/AndroidRuntime(28903): 	at g.d.b.b$b.<init>(SourceFile:1)
E/AndroidRuntime(28903): 	at g.d.b.b.<clinit>(SourceFile:2)
E/AndroidRuntime(28903): 	at g.d.b.e$a.doInBackground(SourceFile:2)
E/AndroidRuntime(28903): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
E/AndroidRuntime(28903): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(28903): 	... 4 more
E/AndroidRuntime(28903): Caused by: java.lang.NoSuchMethodException: values []
E/AndroidRuntime(28903): 	at java.lang.Class.getMethod(Class.java:1981)
E/AndroidRuntime(28903): 	at java.lang.Class.getDeclaredMethod(Class.java:1960)
E/AndroidRuntime(28903): 	at java.lang.Enum$1.create(Enum.java:265)
E/AndroidRuntime(28903): 	... 16 more
D/FlutterGeolocator(28903): Binding to location service.
D/FlutterGeolocator(28903): Destroying location service.
D/FlutterGeolocator(28903): Stop service in foreground.

How to solve it?

**Comment by alibt** [comment]
I got the same problem!
**Flutter Doctor :**
` Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-IR)
    • Flutter version 2.8.1 at /Users/alibakhtiyari/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1`


  **Exception Message On Crashlytics :** 
  `Fatal Exception: java.lang.RuntimeException: java.lang.NoSuchMethodException: b.d.c.e.values []
       at java.lang.Enum.enumValues(Enum.java:270)
       at java.lang.Enum.access$000(Enum.java:61)
       at java.lang.Enum$1.create(Enum.java:277)
       at java.lang.Enum$1.create(Enum.java:275)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Class.getEnumConstantsShared(Class.java:2428)
       at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
       at java.util.EnumMap.<init>(EnumMap.java:138)
       at com.journeyapps.barcodescanner.DefaultDecoderFactory.createDecoder(DefaultDecoderFactory.java:4)
       at com.journeyapps.barcodescanner.BarcodeView.createDecoder(BarcodeView.java:2)
       at com.journeyapps.barcodescanner.BarcodeView.startDecoderThread(BarcodeView.java:21)
       at com.journeyapps.barcodescanner.BarcodeView.previewStarted(BarcodeView.java)
       at com.journeyapps.barcodescanner.CameraPreview.startCameraPreview(CameraPreview.java:28)
       at com.journeyapps.barcodescanner.CameraPreview.A(CameraPreview.java:48)
       at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:5)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:13)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

**Comment by chavesgu** [comment]
Sorry, I 'm busy. Give me more time

**Comment by chavesgu** [comment]
@saelco   I upgrade flutter to 1.10.2. Work fine

**Comment by alibt** [comment]
@chavesgu did you test on release mode? because it's working fine on debug mode.

**Comment by chavesgu** [comment]
I test release---- On 星期四, 24 二月 2022 13:21:12 +0800  ***@***.******@***.***> wrote ---- 
@chavesgu did you test on release mode? because it's working fine on debug mode.

**Comment by saelco** [comment]
I added it on app\build.gradle and app working in release mode:

minifyEnabled false
shrinkResources false

but I don't know if it's a good solution

**Comment by lobtao** [comment]
> I added it on app\build.gradle and app working in release mode:
> 
> minifyEnabled false shrinkResources false
> 
> but I don't know if it's a good solution

It can really solve the problem

**Comment by watayouxiang** [comment]
i can solve this problem:

-keep class com.google.zxing.**{*;}

**Comment by leofx** [comment]
I solved all my problems; Add two lines of code；
![image](https://user-images.githubusercontent.com/27850030/205537476-249994c7-46e6-433f-b02b-c14f9e2d0823.png)
